# Generated by Django 3.1.7 on 2021-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('creator', models.BigIntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrustedRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrustedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='trusteduser',
            constraint=models.UniqueConstraint(fields=('guild_id', 'user_id'), name='unique_trusted_user'),
        ),
        migrations.AddConstraint(
            model_name='trustedrole',
            constraint=models.UniqueConstraint(fields=('guild_id', 'role_id'), name='unique_trusted_role'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('guild_id', 'name'), name='unique_tag'),
        ),
    ]
