# Generated by Django 2.1.7 on 2019-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.IntegerField()),
                ('maxlevel', models.IntegerField(blank=True, null=True)),
                ('minlevel', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
