# Generated by Django 2.1.7 on 2019-03-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('m6rr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constraints',
            new_name='Constraint',
        ),
        migrations.AlterField(
            model_name='constraint',
            name='guild',
            field=models.BigIntegerField(),
        ),
        migrations.RenameField(
            model_name='constraint',
            old_name='rank',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='constraint',
            name='role',
            field=models.BigIntegerField(),
        ),
    ]
